### ISSUE TITLE
shorthand `-` in classes should ERROR

### ISSUE THREAD

**Issue by bennypowers** [tree-sitter/tree-sitter-regex#16]
```
$ cat shorthand.re
/[\w-.]/
$ tree-sitter parse shorthand.re
(pattern [0, 0] - [1, 0]
  (term [0, 0] - [0, 8]
    (pattern_character [0, 0] - [0, 1])
    (character_class [0, 1] - [0, 7]
      (class_range [0, 2] - [0, 6]
        (character_class_escape [0, 2] - [0, 4])
        (class_character [0, 5] - [0, 6])))
    (pattern_character [0, 7] - [0, 8])))
```

expected: [error](https://regex101.com/r/5P4Eql/1)

**Comment by the-mikedavis** [comment]
Tree-sitter grammars are usually very permissive and are not meant to be used for validation.

The docs have some notes on how to structure rules:

* https://github.com/tree-sitter/tree-sitter/blob/ccd6bf554d922596ce905730d98a77af368bba5c/docs/section-3-creating-parsers.md?plain=1#L233
* https://github.com/tree-sitter/tree-sitter/blob/ccd6bf554d922596ce905730d98a77af368bba5c/docs/section-3-creating-parsers.md?plain=1#L342-L376

that suggest optimizing the grammar for easy consumption rather than full spec conformance. In this case, if you were looking to mark this as invalid, you could have a highlight query:

```scm
(class_range
  (character_class_escape) @error)
```

which would highlight the `\w`. IMO this is a better indication of the problem than what regex101 provides in this example if you interpret this as an invalid range (albeit it's arguable).

See also similar discussion: https://github.com/tree-sitter/tree-sitter-javascript/issues/209

**Comment by bennypowers** [comment]
The problem isn't the `\w` it's the invalid `-`
This is an interesting case. while regex101 flags it as invalid, regexr allows it https://github.com/bennypowers/nvim-regexplainer/commit/98c45db9268e64e801a4a4eee63f7c15a6f115ef

and firefox and node both run runs it, as well.

Thanks for the background info!
